### ISSUE TITLE
自建翻墙服务器上传 报错 EOF occurred in violation of protocol (_ssl.c:661) 怎么处理

### ISSUE THREAD

**Issue by chrome001** [bannedbook/fanqiang#137]
错误信息如下：

2017-06-17 19:18:01,098 ERROR appcfg.py:2420 An error occurred processing files '['app.yaml', 'gae.py', 'legacy.py']': EOF occurred in violation of protocol (_ssl.c:661). Aborting. 
Traceback (most recent call last):
  File "D:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "D:\Program Files (x86)\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5510, in <module>
    main(sys.argv)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5501, in main
    result = AppCfgApp(argv).Run()
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2975, in Run
    self.action(self)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5157, in __call__
    return method()
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3889, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2410, in DoUpload
    self.error_fh)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "D:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "D:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1268, in _conn_request
    conn.connect()
  File "D:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1014, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "D:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "D:\Program Files (x86)\python\lib\ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "D:\Program Files (x86)\python\lib\ssl.py", line 611, in __init__
    self.do_handshake()
  File "D:\Program Files (x86)\python\lib\ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:661)
2017-06-17 19:18:01 (Process exited with code 1)

参考教程： https://github.com/bannedbook/fanqiang/wiki/GoAgent-v3.2.3---%E8%87%AA%E5%BB%BA%E7%BF%BB%E5%A2%99%E6%9C%8D%E5%8A%A1%E5%99%A8

**Comment by mymatrix2002** [comment]
用goproxy服务端部署程序上传吧，我前两天上传没有问题，goproxy的作者是phuslu(即goagent的原作者)，这是他结束了goagent项目后的另外一个新项目，目前依然更新中。

**Comment by Alvin9999** [comment]
可以用这个教程来部署[自建appid和搜谷歌ip教程（GoAgent版和GoProxy版）](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAappid%E5%92%8C%E6%90%9C%E8%B0%B7%E6%AD%8Cip%E6%95%99%E7%A8%8B%EF%BC%88GoAgent%E7%89%88%E5%92%8CGoProxy%E7%89%88%EF%BC%89)

**Comment by chrome001** [comment]
挂goproxy代理上传成功，我发现用赛风VPN的话 在上传时会报910错误，目前只要解决 怎么在android上用这个了 ，谢楼上两位好心人建议
