### ISSUE TITLE
我也遇到这个问题。感觉这个操作起来没谱。要是有个简单的步骤就好了。

### ISSUE THREAD

**Issue by yzii** [bannedbook/fanqiang#14]
10:28 PM Getting current resource limits.
2016-09-25 22:32:41,565 ERROR appcfg.py:2411 An error occurred processing file '': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in <module>

**Comment by yzii** [comment]
10:28 PM Getting current resource limits.
2016-09-25 22:32:41,565 ERROR appcfg.py:2411 An error occurred processing file '': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 129, in run_file
