### ISSUE TITLE
利用google app engine launcher上传GoAgent的文件时失败

### ISSUE THREAD

**Issue by zyhxhw** [bannedbook/fanqiang#17]
错误提示为：
016-10-06 23:30:21 Running command: "[u'C:\\Python27\\pythonw.exe', '-u', 'C:\\Program 

Files\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Documents and 

Settings\\Administrator/.appcfg_oauth2_tokens', 'update', u'd:\\My 

Documents\\Downloads\\Compressed\\goagent\\goagent']"
11:30 PM Application: zyhxhw7; version: 1
11:30 PM Host: appengine.google.com
11:30 PM Starting update of app: zyhxhw7, version: 1
11:30 PM Getting current resource limits.
2016-10-06 23:38:59,750 ERROR appcfg.py:2411 An error occurred processing file '': [Errno 

10060] . Aborting. 
。。。。。。。。。。。。。。。。。。。。。。。。。。。
You can close this window now.

**Comment by bannedbook** [comment]
。。。。。。。。。。。。。。。。。。。。。。。。。。。
省略的是什么信息

**Comment by zyhxhw** [comment]
省略的就是一些上传文件的过程，很重要吗？

**Comment by zyhxhw** [comment]
2016-10-08 22:27:11 Running command: "['C:\\Python27\\pythonw.exe', '-u', 'C:\\Program Files\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Documents and Settings\\Administrator/.appcfg_oauth2_tokens', 'update', u'd:\\My Documents\\Downloads\\Compressed\\goagent']"
10:27 PM Application: zyhxhw7; version: 1
10:27 PM Host: appengine.google.com
10:27 PM Starting update of app: zyhxhw7, version: 1
10:27 PM Getting current resource limits.
2016-10-08 22:35:51,015 ERROR appcfg.py:2411 An error occurred processing file '': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5497, in <module>
    main(sys.argv)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5488, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2966, in Run
    self.action(self)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5144, in __call__
    return method()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3876, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3929, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3814, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2401, in DoUpload
    self.error_fh)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1709, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2016-10-08 22:35:51 (Process exited with code 1)

You can close this window now.

**Comment by zyhxhw** [comment]
各位看一下，到底是哪儿的问题，谢谢。

**Comment by bannedbook** [comment]
翻墙了吗，设置IE代理为翻墙软件代理了没

**Comment by zyhxhw** [comment]
如何设置IE代理为翻墙软件呢？谢谢！

2016-10-09 10:36 GMT+08:00 如何翻墙 <notifications@github.com>:

**Comment by zyhxhw** [comment]
不是一些地址、端口吗？

2016-10-09 18:39 GMT+08:00 zyhxhw zyhxhw <zyhxhw@gmail.com>:

**Comment by bannedbook** [comment]
打开我发的Chrome一键翻墙包，并确保能正常打开墙外网站，然后不要关闭代理软件那个黑色窗口。
将IE代理服务器设置成127.0.0.1:8087

**Comment by qianjiakai** [comment]
我也是跟上面情况一样，怎么回事，IE代理已经设置了，代理软件也没关，到底怎么回事？ @bannedbook

**Comment by qianjiakai** [comment]
不行，只有欢迎界面 @bannedbook

**Comment by bannedbook** [comment]
那你换个翻墙方式，并把ie代理设为那个翻墙方式的代理，
这样来试试看
