### ISSUE TITLE
Google App Engine  Deploy socket.error: [Errno 10060] 

### ISSUE THREAD

**Issue by zhangcz2013** [bannedbook/fanqiang#170]
04:41 PM Host: appengine.google.com
04:41 PM Starting update of app: zhangcz2013, version: 1
04:41 PM Getting current resource limits.
2017-10-10 16:49:48,305 ERROR appcfg.py:2420 An error occurred processing files '['app.yaml', 'app.yaml.bak', 'gae.py', 'legacy.py']': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5510, in <module>
    main(sys.argv)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5501, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2975, in Run
    self.action(self)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5157, in __call__
    return method()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3889, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2410, in DoUpload
    self.error_fh)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2017-10-10 16:49:48 (Process exited with code 1)

You can close this window now.

**Comment by ycountJavaXuan** [comment]
Why are you CC to me ????? ZhangCZ


在 2017年10月10日，17:12，zhangcz2013 <notifications@github.com<mailto:notifications@github.com>> 写道：


04:41 PM Host: appengine.google.com<http://appengine.google.com>
04:41 PM Starting update of app: zhangcz2013, version: 1
04:41 PM Getting current resource limits.
2017-10-10 16:49:48,305 ERROR appcfg.py:2420 An error occurred processing files '['app.yaml', 'app.yaml.bak', 'gae.py', 'legacy.py']': [Errno 10060] . Aborting.
Traceback (most recent call last):
File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in
run_file(file, globals())
File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 129, in run_file
execfile(PATHS.script_file(script_name), globals)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5510, in
main(sys.argv)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5501, in main
result = AppCfgApp(argv).Run()
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2975, in Run
self.action(self)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5157, in call
return method()
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3889, in Update
self._UpdateWithParsedAppYaml(appyaml, self.basepath)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
return appversion.DoUpload(paths, openfunc)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2410, in DoUpload
self.error_fh)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
resource_limits.update(_GetRemoteResourceLimits(logging_context))
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in GetRemoteResourceLimits
yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
result = self.rpcserver.Send(url, payload=payload, **kwargs)
File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
url, method=method, body=payload, headers=headers)
File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2_init.py", line 1584, in request
(response, content) = self.request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2_init.py", line 1332, in _request
(response, content) = self.conn_request(conn, request_uri, method, body, headers)
File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2_init.py", line 1306, in conn_request
conn.connect()
File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2_init.py", line 1053, in connect
raise socket.error, msg
socket.error: [Errno 10060]
2017-10-10 16:49:48 (Process exited with code 1)

You can close this window now.

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
