### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by waterlogithub** [bannedbook/fanqiang#20]
2016-10-10 20:44:51 Running command: "['C:\\Python27\\pythonw.exe', '-u', 'C:\\Program Files\\Google\\google_appengine\\appcfg.py', 

'--oauth2_credential_file=C:\\Users\\Administrator/.appcfg_oauth2_tokens', 'update', u'D:\\Program Files\\goagent3\\server\\gae']"
08:44 PM Application: formyhtcg1806; version: 1
08:44 PM Host: appengine.google.com
08:44 PM Starting update of app: myappid06, version: 1
08:44 PM Getting current resource limits.
08:45 PM Scanning files on local disk.
08:45 PM Cloning 4 application files.
2016-10-10 20:48:22,118 ERROR appcfg.py:2578 An unexpected error occurred. Aborting. 
Traceback (most recent call last):
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2415, in DoUpload
    missing_files = self.Begin()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2008, in Begin
    CloneFiles('/api/appversion/clonefiles', files_to_clone, 'application')
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1996, in CloneFiles
    payload=BuildClonePostBody(chunk))
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1709, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files\Google\google_appengine\lib\oauth2client\oauth2client\client.py", line 569, in new_request
    redirections, connection_type)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1014, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "C:\Python27\lib\ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
08:48 PM Rolling back the update.
Traceback (most recent call last):
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "C:\Program Files\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5497, in <module>
    main(sys.argv)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5488, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2966, in Run
    self.action(self)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5144, in __call__
    return method()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3876, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3929, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3814, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2415, in DoUpload
    missing_files = self.Begin()
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2008, in Begin
    CloneFiles('/api/appversion/clonefiles', files_to_clone, 'application')
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1996, in CloneFiles
    payload=BuildClonePostBody(chunk))
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1709, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files\Google\google_appengine\lib\oauth2client\oauth2client\client.py", line 569, in new_request
    redirections, connection_type)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1014, in connect
    self.disable_ssl_certificate_validation, self.ca_certs)
  File "C:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 80, in _ssl_wrap_socket
    cert_reqs=cert_reqs, ca_certs=ca_certs)
  File "C:\Python27\lib\ssl.py", line 933, in wrap_socket
    ciphers=ciphers)
  File "C:\Python27\lib\ssl.py", line 601, in __init__
    self.do_handshake()
  File "C:\Python27\lib\ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:590)
2016-10-10 20:48:26 (Process exited with code 1)

You can close this window now.

是哪里出问题了呢？

**Comment by bannedbook** [comment]
是否设置了ie代理，用ie可以打开google吗

**Comment by waterlogithub** [comment]
可以打开google @bannedbook

**Comment by esc0755** [comment]
我也是出现部署失败的问题，但和楼上的问题应该是不一样。具体如下，麻烦帮忙看看，谢谢！
2016-10-17 04:19:00 Running command: "['D:\\Program Files\\Python\\pythonw.exe', '-u', 'D:\\Program Files\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Documents and Settings\\David Zhu/.appcfg_oauth2_tokens', 'update', u'D:\\Firefox\\DavidFQ\\2015-6-updata\\goagent-goagent-985cbd5\\server\\gae']"
04:19 AM Application: davidfq001; version: 1
04:19 AM Host: appengine.google.com
04:19 AM Starting update of app: davidfq001, version: 1
04:19 AM Getting current resource limits.
2016-10-17 04:27:34,483 ERROR appcfg.py:2411 An error occurred processing file '': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "D:\Program Files\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "D:\Program Files\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5497, in <module>
    main(sys.argv)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5488, in main
    result = AppCfgApp(argv).Run()
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2966, in Run
    self.action(self)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5144, in __call__
    return method()
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3876, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3929, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3814, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2401, in DoUpload
    self.error_fh)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1709, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2016-10-17 04:27:34 (Process exited with code 1)

You can close this window now.

**Comment by bannedbook** [comment]
个人感觉socket.error 可能都是因为网络连接失败，本身不一定有什么问题

**Comment by waterlogithub** [comment]
刚才重试出现以下错误，请问这是什么问题？

2016-10-22 19:00:24 Running command: "['C:\\Python27\\pythonw.exe', '-u', 'C:\\Program Files\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Users\\Administrator/.appcfg_oauth2_tokens', 'update', 'D:\\Program Files\\goagent3\\server\\gae']"
Usage: appcfg.py [options] update <directory> | [file, ...]

appcfg.py: error: Error parsing D:\Program Files\goagent3\server\gae\app.yaml: mapping values are not allowed here
  in "D:\Program Files\goagent3\server\gae\app.yaml", line 1, column 34.
2016-10-22 19:00:25 (Process exited with code 2)

You can close this window now.

**Comment by esc0755** [comment]
尝试了多次，一直是提示这个socket error 10060错误出现。
不知部署已申请的帐号是否还有其他的不使用GAE Launcher那个软件的方法？
即使麻烦一些也可以，但这样一直不能部署成功，直接搞得很无奈了都。
谢谢！

**Comment by bannedbook** [comment]
10060 连接服务器超时，有人 建议挂VPN后再上传，可能还是翻墙问题，先翻好墙再上传
