### ISSUE TITLE
点击Deploy 出现错误 并没有自动弹出浏览器! IE已经能正常访问谷歌，谢谢！

### ISSUE THREAD

**Issue by yaoxiaobo** [bannedbook/fanqiang#212]
2017-12-11 15:50:16 Running command: "['D:\\Python27\\pythonw.exe', '-u', 'D:\\Program Files\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Users\\Administrator/.appcfg_oauth2_tokens', 'update', u'E:\\Soft\\green\\FQHJ\\freeman\\GAE\\goagent\\goagent']"
03:50 PM Application: extended-ascent-184002; version: 1
03:50 PM Host: appengine.google.com
03:50 PM Starting update of app: extended-ascent-184002, version: 1
03:50 PM Getting current resource limits.
2017-12-11 15:51:45,375 ERROR appcfg.py:2420 An error occurred processing files '['app.yaml', 'gae.py', 'legacy.py']': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "D:\Program Files\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "D:\Program Files\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5510, in <module>
    main(sys.argv)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5501, in main
    result = AppCfgApp(argv).Run()
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2975, in Run
    self.action(self)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 5157, in __call__
    return method()
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3889, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 2410, in DoUpload
    self.error_fh)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "D:\Program Files\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "D:\Program Files\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2017-12-11 15:51:45 (Process exited with code 1)

You can close this window now.

**Comment by bannedbook** [comment]
connect
raise socket.error

可能没有翻墙成功，或ie代理没有正确设置吧

**Comment by bannedbook** [comment]
也可以试试这个新方法：
[GoAgent 自建appid](https://github.com/bannedbook/fanqiang/wiki/GoAgent-v3.2.3---%E8%87%AA%E5%BB%BA%E7%BF%BB%E5%A2%99%E6%9C%8D%E5%8A%A1%E5%99%A8)
