### ISSUE TITLE
上传不了APPID了

### ISSUE THREAD

**Issue by djangoja** [bannedbook/fanqiang#225]
APPID:xxx
04:00 PM Application: xxx
04:00 PM Host: appengine.google.com
04:00 PM Rolling back the update.
Traceback (most recent call last):
  File "python27.py", line 95, in <module>
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\uploader.py", line 149, in <module>
    main()
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\uploader.py", line 143, in main
    upload('gae', appid)
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\uploader.py", line 111, in upload
    appcfg.main(['appcfg', 'rollback', dirname])
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 5514, in main
    result = AppCfgApp(argv).Run()
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 2977, in Run
    self.action(self)
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 5170, in __call__
    return method()
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 4523, in Rollback
    self._Rollback()
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 4568, in _Rollback
    appversion.Rollback(force_rollback)
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 2387, in Rollback
    force_rollback='1' if force_rollback else '0')
  File "C:\Users\xujingjie\Desktop\fanqing\goproxy-r73\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "google_appengine\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "google_appengine\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "google_appengine\httplib2\__init__.py", line 1268, in _conn_request
    conn.connect()
  File "google_appengine\httplib2\__init__.py", line 1011, in connect
    sock.connect((self.host, self.port))
  File "PySocks\socks.py", line 740, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080: [Errno 10060]
请按任意键继续. . .

**Comment by bannedbook** [comment]
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:1080
是不是代理设置错了，用IE可以翻墙吗

**Comment by djangoja** [comment]
可以的，可以翻墙。 我发现关了原来的代理就可以上传上去了

**Comment by yiasoall** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
