### ISSUE TITLE
[Errno 10051] 向一个无法连接的网络尝试了一个套接字操作。

### ISSUE THREAD

**Issue by 1576316115** [bannedbook/fanqiang#270]
经常出现题目所示的问题。
黑框提示的消息：
Traceback (most recent call last):
  File "E:\ChromeDownloads\ChromeGo\ipv6-Agent0\proxylib.py", line 2078, in create_http_request
  File "E:\ChromeDownloads\ChromeGo\ipv6-Agent0\proxylib.py", line 2057, in create_ssl_connection
error: [Errno 10051] 向一个无法连接的网络尝试了一个套接字操作。
各位遇见过该情况的，求解！谢谢！

**Comment by bannedbook** [comment]
进 ip_Update 目录, 执行  ip_1.bat 更新下ip试试看

**Comment by 1576316115** [comment]
问题依旧，我试一下把Chrome卸载，再重新安装翻墙看看。谢谢你给的建议！

**Comment by bannedbook** [comment]
换 ipv6-Agent1 可以吗

**Comment by 1576316115** [comment]
检测ipv6时发现异常，重置电脑的ipv6配置后，现在问题解决了。谢谢！
