### ISSUE TITLE
[Errno 10053] 你的主机中的软件中止了一个已建立的连接。

### ISSUE THREAD

**Issue by 1576316115** [bannedbook/fanqiang#272]
GoAgent ipv6 版 黑框提示错误：
ERROR - [Apr 02 18:06:00] create_http_request "POST https://p1y5y54pp1iyp1-005.appspot.com/_gh/" failed:[Errno 10053] 你的主机中的软件中止了一个已建立的连接。
Traceback (most recent call last):
  File "E:\ChromeDownloads\ChromeGo\ipv6-Agent0\proxylib.py", line 2078, in create_http_request
  File "E:\ChromeDownloads\ChromeGo\ipv6-Agent0\proxylib.py", line 2057, in create_ssl_connection
error: [Errno 10053] 你的主机中的软件中止了一个已建立的连接。
望有经验者帮忙解答一下，谢谢！
（PS：电脑没有安装任何国产杀毒软件，只有windows10自带杀毒程序）

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/issues/270
看看有没有参考性
