### ISSUE TITLE
goagent自建流量(appid)时出错:getting current resource limits

### ISSUE THREAD

**Issue by bannedbook** [bannedbook/fanqiang#5]
goagent自建流量(appid)时出错

**Comment by OneDirection9** [comment]
我也遇到了一样的情况，请问你最后解决了吗？

**Comment by bannedbook** [comment]
这个提示好像不影响，不算一个错误，你要看看还有没有其它的错误提示

**Comment by OneDirection9** [comment]
在get current resource limits之后，等待了一会儿， 就会出现下面的报错。

2016-09-13 10:39:02,822 ERROR appcfg.py:2411 An error occurred processing file '': [Errno 10060] . Aborting. 
Traceback (most recent call last):
 "D:\GAESDK\appcfg.py", line 133, in \<module\>
　　run_file(__file__, globals())
  File "D:\GAESDK\appcfg.py", line 129, in run_file
　　execfile(_PATHS.script_file(script_name), globals_)
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 5497, in \<module\>
　　main(sys.argv)
  File "D:\fanqiang\GAESDK\google\appengine\tools\appcfg.py", line 5488, in main
　　result = AppCfgApp(argv).Run()
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 2966, in Run
　　self.action(self)
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 5144, in __call__
　　return method()
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 3876, in Update
　　self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 3929, in _UpdateWithParsedAppYaml
　　self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 3814, in UpdateVersion
　　return appversion.DoUpload(paths, openfunc)
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 2401, in DoUpload
　　self.error_fh)
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
　　resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
　　yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "D:\GAESDK\google\appengine\tools\appcfg.py", line 1709, in Send
　　result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "D:\GAESDK\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
　　url, method=method, body=payload, headers=headers)
  File "D:\GAESDK\lib\httplib2\httplib2\__init__.py", line 1584, in request
　　(response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "D:\GAESDK\lib\httplib2\httplib2\__init__.py", line 1332, in _request
　　(response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "D:\fanqiang\GAESDK\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
　　conn.connect()
  File "D:\GAESDK\lib\httplib2\httplib2\__init__.py", line 1053, in connect
　　raise socket.error, msg
socket.error: [Errno 10060] 
2016-09-13 10:39:02 (Process exited with code 1)

**Comment by bannedbook** [comment]
翻墙了没，把翻墙用的代理设置为ie代理了吗

**Comment by OneDirection9** [comment]
翻了。我之前已经按照教程走过一遍成功了。但是想再申请一个就出现这个问题了。实现不行就放弃了

**Comment by OneDirection9** [comment]
在使用GAE deploy的时候，端口有影响吗？

**Comment by bannedbook** [comment]
有没有更换google账号，还是只是同一个账号的另外一个appid？

**Comment by OneDirection9** [comment]
同一个账号的APPid。感觉账号这个，是在自动弹出浏览器页面的时候才登陆的吧

**Comment by sharebookc** [comment]
装好桌面上没有Google App Engine Launcher这个，只有Google Cloud SDK Shell 怎么弄  谢谢

**Comment by OneDirection9** [comment]
Windows下查找一下就可以了吧。



在 2017-01-25 00:29:27，"sharebookc" <notifications@github.com> 写道：


装好桌面上没有Google App Engine Launcher这个，只有Google Cloud SDK Shell 怎么弄 谢谢

**Comment by ComputerWizard2** [comment]
我也遇到了同样的问题，请问你最后是怎么解决的.

**Comment by sharebookc** [comment]
windows下也没有。安装目录只有这两个
![qq 20170127232527](https://cloud.githubusercontent.com/assets/25324715/22376255/3b119572-e4e8-11e6-896f-c36ac8e2fe14.jpg)
