### ISSUE TITLE
点击Deploy之后没有出现应有的弹出页面

### ISSUE THREAD

**Issue by plsshutup** [bannedbook/fanqiang#89]
![default](https://cloud.githubusercontent.com/assets/26184919/23579037/57c010c4-011f-11e7-9868-db4ad19608e5.PNG)
而且这个东西一直这样停着，没有出现you can close......那些的。

最下一行是是说出了什么错吗？

参考了一下其他人发的求助帖，还是没有解决。

appid没有输入错误，格式应该也没有问题，检查了好几次了……泪奔

**Comment by plsshutup** [comment]
刚刚似乎运行结束了……出来这些东西


2017-03-04 21:07:34 Running command: "['C:\\Python27\\pythonw.exe', '-u', 'C:\\Program Files (x86)\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Users\\Sun Tsai/.appcfg_oauth2_tokens', 'update', u'C:\\Users\\Sun Tsai\\Downloads\\goagent\\goagent']"
09:07 PM Application: yangyingmum; version: 1
09:07 PM Host: appengine.google.com
09:07 PM Starting update of app: yangyingmum, version: 1
09:07 PM Getting current resource limits.
2017-03-04 21:16:05,766 ERROR appcfg.py:2420 An error occurred processing files '['app.yaml', 'gae.py', 'legacy.py']': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5510, in <module>
    main(sys.argv)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5501, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2975, in Run
    self.action(self)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5157, in __call__
    return method()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3889, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2410, in DoUpload
    self.error_fh)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2017-03-04 21:16:05 (Process exited with code 1)

You can close this window now.

**Comment by bannedbook** [comment]
没翻墙成功？ie能访问google吗

**Comment by nianyuyu** [comment]
我也出现了这种情况，ie可以访问谷歌~

**Comment by yangtao4389** [comment]
用你分享的goagent能打开google，但是用自带的ie不行。难道要自带的ie在用其他方法先设置好代理的情况下才能进行下一步吗？表示跟楼主遇到一样的情况

**Comment by bannedbook** [comment]
要设置好ie代理，把ie代理设置成goagent代理
