### ISSUE TITLE
点击Deploy之后过好久提示错误

### ISSUE THREAD

**Issue by gwjczwy** [bannedbook/fanqiang#90]
我觉着应该是挂代理和设置IE代理服务器为127.0.0.1这个过程出了问题。
把代理服务器改成127.0.0.1之后不就无法上网了吗？
对这个过程不是很懂，要先改为127.0.0.1还是先打开VPN？
以下是错误信息：

2017-03-05 20:11:14 Running command: "['C:\\ProgramData\\Miniconda3\\envs\\python27\\pythonw.exe', '-u', 'C:\\Program Files (x86)\\Google\\google_appengine\\appcfg.py', '--oauth2_credential_file=C:\\Users\\Administrator/.appcfg_oauth2_tokens', 'update', 'C:\\Users\\Administrator\\Desktop\\goagent']"
08:11 PM Application: arnoux-149706; version: 1
08:11 PM Host: appengine.google.com
08:11 PM Starting update of app: arnoux-149706, version: 1
08:11 PM Getting current resource limits.
2017-03-05 20:19:44,867 ERROR appcfg.py:2420 An error occurred processing files '['GoAgent.pdf', 'app.yaml', 'gae.py', 'legacy.py']': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "C:\Program Files (x86)\Google\google_appengine\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5510, in <module>
    main(sys.argv)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5501, in main
    result = AppCfgApp(argv).Run()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2975, in Run
    self.action(self)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 5157, in __call__
    return method()
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3889, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 2410, in DoUpload
    self.error_fh)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "C:\Program Files (x86)\Google\google_appengine\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "C:\Program Files (x86)\Google\google_appengine\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2017-03-05 20:19:45 (Process exited with code 1)

You can close this window now.

**Comment by bannedbook** [comment]
挂VPN就不要设置代理，用一种翻墙方式，确保ie能访问google

**Comment by gwjczwy** [comment]
谢谢你，已经解决了！
