### ISSUE TITLE
GoAgent v3.2.3 自建翻墙服务器失败

### ISSUE THREAD

**Issue by earvinlion** [bannedbook/fanqiang#94]
如题，首次使用Goagent及Chrome一键翻墙包。
点击Goagent翻墙顺利打开新Chrome网页，但原Chrome上的网页却还是打不开，需要粘贴过来。
而且速度不快，于是就想自建服务器。
顺利于Google App Engine建立几个project。但deploy时即出现问题，等待许久还是失败：
![deployment to google](https://cloud.githubusercontent.com/assets/26291959/23735091/7b25beea-04be-11e7-8aa4-0764e8d371ce.png)
2017-03-09 11:00:30 Running command: "['F:\\ChromeGo-lite\\Pathon 2.7.13\\pythonw.exe', '-u', 'F:\\ChromeGo-lite\\appcfg.py', '--oauth2_credential_file=C:\\Users\\earvin/.appcfg_oauth2_tokens', 'update', 'F:\\ChromeGo-lite\\goagent']"
11:00 AM Application: my-project2-160913; version: 1
11:00 AM Host: appengine.google.com
11:00 AM Starting update of app: my-project2-160913, version: 1
11:00 AM Getting current resource limits.
2017-03-09 11:09:10,756 ERROR appcfg.py:2420 An error occurred processing files '['GoAgent.pdf', 'app.yaml', 'gae.py', 'legacy.py', 'engineapp/app.yaml', 'engineapp/favicon.ico', 'engineapp/index.yaml', 'engineapp/main.py']': [Errno 10060] . Aborting. 
Traceback (most recent call last):
  File "F:\ChromeGo-lite\appcfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "F:\ChromeGo-lite\appcfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 5510, in <module>
    main(sys.argv)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 5501, in main
    result = AppCfgApp(argv).Run()
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 2975, in Run
    self.action(self)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 5157, in __call__
    return method()
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 3889, in Update
    self._UpdateWithParsedAppYaml(appyaml, self.basepath)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 3942, in _UpdateWithParsedAppYaml
    self.UpdateVersion(rpcserver, basepath, appyaml, APP_YAML_FILENAME)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 3824, in UpdateVersion
    return appversion.DoUpload(paths, openfunc)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 2410, in DoUpload
    self.error_fh)
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 497, in GetResourceLimits
    resource_limits.update(_GetRemoteResourceLimits(logging_context))
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 467, in _GetRemoteResourceLimits
    yaml_data = logging_context.Send('/api/appversion/getresourcelimits')
  File "F:\ChromeGo-lite\google\appengine\tools\appcfg.py", line 1719, in Send
    result = self.rpcserver.Send(url, payload=payload, **kwargs)
  File "F:\ChromeGo-lite\google\appengine\tools\appengine_rpc_httplib2.py", line 246, in Send
    url, method=method, body=payload, headers=headers)
  File "F:\ChromeGo-lite\lib\httplib2\httplib2\__init__.py", line 1584, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "F:\ChromeGo-lite\lib\httplib2\httplib2\__init__.py", line 1332, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "F:\ChromeGo-lite\lib\httplib2\httplib2\__init__.py", line 1306, in _conn_request
    conn.connect()
  File "F:\ChromeGo-lite\lib\httplib2\httplib2\__init__.py", line 1053, in connect
    raise socket.error, msg
socket.error: [Errno 10060] 
2017-03-09 11:09:11 (Process exited with code 1)

You can close this window now.

**Comment by bannedbook** [comment]
是否已翻墙设置ie代理，用ie访问google看看能否访问

**Comment by nianyuyu** [comment]
问题一样，IE可以访问google,请问你解决了吗？

**Comment by earvinlion** [comment]
deploy前按步骤设置了IE代理，deploy失败后也继续执行其他步骤，未能访问google

**Comment by Jeremyshilintong** [comment]
我也碰到这样的问题
